logging:
  level:
    root: info
    com.masuguar.foolish.resposity.mapper: debug
mybatis:
  mapperLocations: classpath:mapping/*.xml
mapper:
  mappers: com.masuguar.foolish.resposity.base.CommonMapper
  notEmpty: true
  before: true

server:
  port: 9898
spring:
  profiles:
    active: pg


---
#h2环境
spring:
  profiles: h2
  datasource:
    driver-class-name: org.h2.Driver
    password: Abc12345
    platform: h2
    schema: classpath:db/schema.sql
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: root
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---
#pg数据库
spring:
  profiles: pg
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    username: postgres
    password: Abc12345
    url: jdbc:postgresql://127.0.0.1:5432/showCode?useSSL=false